# Generated by Django 6.0.4 on 2026-06-05 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                (
                    "channel",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("EMAIL", "Email")], max_length=10
                    ),
                ),
                ("comm_type", models.CharField(max_length=30)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("ai_drafted", models.BooleanField(default=True)),
                ("ai_rationale", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_APPROVAL", "Pending Officer Approval"),
                            ("APPROVED", "Approved — Ready to Send"),
                            ("REJECTED", "Rejected by Officer"),
                            ("SENT", "Sent"),
                            ("FAILED", "Send Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_APPROVAL",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "notification_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivered", models.BooleanField(default=False)),
                ("delivery_timestamp", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="notifications.notificationqueue",
                    ),
                ),
            ],
            options={
                "db_table": "notification_logs",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comm_type",
                    models.CharField(
                        choices=[
                            ("REPAYMENT_REMINDER", "Repayment Reminder"),
                            ("OVERDUE_REMINDER", "Overdue Payment Reminder"),
                            ("PTP_REMINDER", "Promise to Pay Reminder"),
                            ("LOAN_APPROVED", "Loan Approval Notification"),
                            ("LOAN_REJECTED", "Loan Rejection Notification"),
                            ("STAFF_ESCALATION_ALERT", "Staff Escalation Alert"),
                            ("FRAUD_ALERT_NOTIFY", "Fraud Alert Notification"),
                            ("GENERAL", "General Communication"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("BOTH", "SMS and Email"),
                        ],
                        default="BOTH",
                        max_length=10,
                    ),
                ),
                ("sms_template", models.TextField()),
                ("email_subject_template", models.CharField(max_length=255)),
                ("email_body_template", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_templates",
                "unique_together": {("comm_type", "language")},
            },
        ),
    ]
