# Generated by Django 6.0.4 on 2026-06-02 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0004_disbursementcondition_loan_disbursement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelinquencyCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PROMISE_TO_PAY", "Promise to Pay Received"),
                            ("ESCALATED", "Escalated"),
                            ("RESOLVED", "Resolved"),
                            ("WRITTEN_OFF", "Written Off"),
                            ("LEGAL", "Referred to Legal"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("BUCKET_1_7", "1–7 Days Overdue"),
                            ("BUCKET_8_30", "8–30 Days Overdue"),
                            ("BUCKET_OVER_30", "30+ Days Overdue"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_overdue_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("days_overdue", models.IntegerField(default=0)),
                ("overdue_installments_count", models.IntegerField(default=0)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_collection_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_delinquency_case",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "collection_delinquency_cases",
                "ordering": ["-days_overdue"],
            },
        ),
        migrations.CreateModel(
            name="CollectionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("PHONE_CALL", "Phone Call"),
                            ("SMS", "SMS Sent"),
                            ("EMAIL", "Email Sent"),
                            ("FIELD_VISIT", "Field Visit"),
                            ("WRITTEN_NOTICE", "Written Notice Sent"),
                            ("GUARANTOR_CONTACT", "Guarantor Contacted"),
                            ("INTERNAL_NOTE", "Internal Note"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("NO_ANSWER", "No Answer"),
                            ("CONTACTED", "Client Contacted"),
                            ("PROMISED_PAYMENT", "Promised to Pay"),
                            ("REFUSED", "Refused to Pay"),
                            ("DISPUTE", "Payment in Dispute"),
                            ("UNREACHABLE", "Client Unreachable"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField()),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="collections.delinquencycase",
                    ),
                ),
            ],
            options={
                "db_table": "collection_actions",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("30_DAYS_OVERDUE", "30+ Days Overdue"),
                            ("BROKEN_PROMISE", "Repeated Broken Promises"),
                            ("UNREACHABLE", "Client Unreachable"),
                            ("DISPUTE", "Dispute Raised"),
                            ("LEGAL_RISK", "Legal Action Risk"),
                            ("FRAUD_SUSPICION", "Fraud Suspicion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField()),
                ("escalated_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="collections.delinquencycase",
                    ),
                ),
                (
                    "escalated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "escalation_records",
                "ordering": ["-escalated_at"],
            },
        ),
        migrations.CreateModel(
            name="PromiseToPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promised_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("promised_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("KEPT", "Promise Kept"),
                            ("BROKEN", "Promise Broken"),
                            ("EXTENDED", "Extended"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("outcome_notes", models.TextField(blank=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promises",
                        to="collections.delinquencycase",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promises_to_pay",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
