# Generated by Django 6.0.4 on 2026-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delinquencycase",
            name="behavioral_pattern_label",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="delinquencycase",
            name="llm_recommended_action",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="delinquencycase",
            name="predicted_default_probability",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
