# Generated by Django 6.0.4 on 2026-06-24 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_attempted", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("success", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "login_attempts",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status_after",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status_before",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("CREATE", "Create Record"),
                    ("UPDATE", "Update Record"),
                    ("DELETE", "Delete / Deactivate"),
                    ("STATUS_CHANGE", "Status Change"),
                    ("APPROVAL", "Approval Decision"),
                    ("DISBURSEMENT", "Loan Disbursement"),
                    ("PAYMENT", "Payment Posted"),
                    ("AI_ACTION", "AI Agent Action"),
                    ("OVERRIDE", "AI Override by Human"),
                    ("ESCALATION", "Case Escalation"),
                    ("FRAUD_ACTION", "Fraud / Compliance Action"),
                    ("PERMISSION_CHANGE", "Permission / Role Change"),
                    ("EXPORT", "Data Export"),
                    ("SYSTEM", "System Event"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AgentActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        choices=[
                            ("A1", "Data Collection Agent"),
                            ("A2", "Risk Assessment Agent"),
                            ("A3", "Recommendation Agent"),
                            ("A4", "Monitoring Agent"),
                            ("A5", "Fraud Detection Agent"),
                            ("A6", "Communication Agent"),
                        ],
                        max_length=5,
                    ),
                ),
                ("agent_name", models.CharField(max_length=50)),
                ("trigger_type", models.CharField(blank=True, max_length=50)),
                ("input_reference", models.CharField(blank=True, max_length=100)),
                ("input_payload", models.JSONField(default=dict)),
                ("output_payload", models.JSONField(default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("rationale", models.TextField(blank=True)),
                ("invoked_at", models.DateTimeField(auto_now_add=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_action_logs",
                "ordering": ["-invoked_at"],
            },
        ),
        migrations.CreateModel(
            name="HumanDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("officer_role", models.CharField(blank=True, max_length=50)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("LOAN_APPROVAL", "Loan Approval"),
                            ("LOAN_REJECTION", "Loan Rejection"),
                            ("AI_OVERRIDE", "AI Recommendation Override"),
                            ("ESCALATION_APPROVE", "Escalation Approved"),
                            ("COMMITTEE_VOTE", "Committee Vote"),
                            ("DISBURSEMENT_AUTH", "Disbursement Authorization"),
                            ("FRAUD_DECISION", "Fraud Investigation Decision"),
                            ("COMPLIANCE_ACTION", "Compliance Action"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference_model", models.CharField(blank=True, max_length=100)),
                ("reference_id", models.CharField(blank=True, max_length=50)),
                ("decision", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                ("ai_recommendation", models.CharField(blank=True, max_length=50)),
                ("followed_ai", models.BooleanField(blank=True, null=True)),
                ("override_justification", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="human_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "human_decision_logs",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_role", models.CharField(blank=True, max_length=50)),
                ("new_role", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "permission_change_logs",
                "ordering": ["-changed_at"],
            },
        ),
    ]
