# Generated by Django 6.0.4 on 2026-06-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_loginattempt_auditlog_status_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentactionlog",
            name="completion_tokens_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentactionlog",
            name="hallucination_check_passed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agentactionlog",
            name="input_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="agentactionlog",
            name="llm_model_used",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="agentactionlog",
            name="llm_raw_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agentactionlog",
            name="prompt_tokens_used",
            field=models.IntegerField(default=0),
        ),
    ]
