# Generated by Django 6.0.4 on 2026-06-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_agentactionlog_completion_tokens_used_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("DEGRADED", "Degraded"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="ONLINE",
                        max_length=10,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("last_online", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("manual_mode_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "ai_service_status",
            },
        ),
        migrations.CreateModel(
            name="SystemIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_type", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("SOFT", "Soft Failure — Low Confidence Response"),
                            ("HARD", "Hard Failure — Service Unreachable"),
                            ("PARTIAL", "Partial Failure — Timeout"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("agent_id", models.CharField(blank=True, max_length=5)),
                ("affected_reference", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_incidents",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ManualReviewCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(max_length=5)),
                ("reference_model", models.CharField(max_length=100)),
                ("reference_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Manual Review"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("AI_RETRY_QUEUED", "AI Retry Queued"),
                            ("RESOLVED_BY_AI", "Resolved by AI After Recovery"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("manual_score", models.FloatField(blank=True, null=True)),
                ("manual_decision", models.CharField(blank=True, max_length=100)),
                ("manual_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_after_recovery", models.BooleanField(default=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="audit.systemincident",
                    ),
                ),
            ],
            options={
                "db_table": "manual_review_cases",
                "ordering": ["-created_at"],
            },
        ),
    ]
