# Generated by Django 6.0.4 on 2026-07-02 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_aiservicestatus_systemincident_manualreviewcase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentactionlog",
            name="ai_bypassed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentactionlog",
            name="bypass_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agentactionlog",
            name="execution_mode",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="AgentConfigChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(max_length=5)),
                ("field_changed", models.CharField(max_length=50)),
                ("old_value", models.CharField(max_length=200)),
                ("new_value", models.CharField(max_length=200)),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_config_change_logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        choices=[
                            ("A1", "Data Collection"),
                            ("A2", "Risk Assessment"),
                            ("A3", "Recommendation"),
                            ("A4", "Monitoring"),
                            ("A5", "Fraud Detection"),
                            ("A6", "Communication"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("llm_enabled", models.BooleanField(default=False)),
                ("is_paused", models.BooleanField(default=False)),
                ("pause_reason", models.TextField(blank=True)),
                ("confidence_threshold", models.FloatField(default=0.65)),
                ("model_override", models.CharField(blank=True, max_length=50)),
                ("daily_token_budget", models.IntegerField(blank=True, null=True)),
                ("last_changed_at", models.DateTimeField(auto_now=True)),
                (
                    "last_changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Configuration",
                "verbose_name_plural": "Agent Configurations",
                "db_table": "agent_configurations",
            },
        ),
    ]
