# Generated by Django 6.0.4 on 2026-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_agentactionlog_ai_bypassed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfiguration",
            name="fallback_behavior",
            field=models.CharField(
                choices=[
                    ("RULE_FALLBACK", "Local Rule Engine Fallback"),
                    ("MANUAL_REVIEW", "Queue for Manual Review"),
                    ("REJECT", "Hard Fail"),
                ],
                default="RULE_FALLBACK",
                max_length=30,
            ),
        ),
    ]
