# Generated by Django 6.0.4 on 2026-05-30 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0003_airecommendation_officerfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_RISK_REVIEW", "Pending Risk Analyst Review"),
                            ("PENDING_MANAGER_REVIEW", "Pending Branch Manager Review"),
                            ("PENDING_COMMITTEE", "Pending Credit Committee"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MORE_INFO_REQUIRED", "More Information Required"),
                        ],
                        default="PENDING_RISK_REVIEW",
                        max_length=30,
                    ),
                ),
                ("requires_committee", models.BooleanField(default=False)),
                (
                    "committee_threshold",
                    models.DecimalField(
                        decimal_places=2, default=500000, max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflow",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "db_table": "approval_workflows",
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("RISK_ANALYST", "Risk Analyst Review"),
                            ("BRANCH_MANAGER", "Branch Manager Review"),
                            ("CREDIT_COMMITTEE", "Credit Committee Decision"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MORE_INFO", "More Information Required"),
                            ("ESCALATE", "Escalate to Next Level"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "ai_recommendation_followed",
                    models.BooleanField(blank=True, null=True),
                ),
                ("override_reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="approvals.approvalworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "approval_decisions",
                "ordering": ["decided_at"],
            },
        ),
        migrations.CreateModel(
            name="CommitteeDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        blank=True,
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("vote_for", models.IntegerField(default=0)),
                ("vote_against", models.IntegerField(default=0)),
                ("quorum_reached", models.BooleanField(default=False)),
                ("meeting_notes", models.TextField(blank=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_decision",
                        to="approvals.approvalworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "committee_decisions",
            },
        ),
    ]
