# Generated by Django 6.0.4 on 2026-05-24 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("min_duration_months", models.IntegerField()),
                ("max_duration_months", models.IntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "loan_products",
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("requested_duration_months", models.IntegerField()),
                (
                    "loan_purpose",
                    models.CharField(
                        choices=[
                            ("BUSINESS_EXPANSION", "Business Expansion"),
                            ("WORKING_CAPITAL", "Working Capital"),
                            ("EQUIPMENT_PURCHASE", "Equipment Purchase"),
                            ("AGRICULTURE", "Agriculture"),
                            ("EDUCATION", "Education"),
                            ("MEDICAL", "Medical Emergency"),
                            ("HOME_IMPROVEMENT", "Home Improvement"),
                            ("DEBT_CONSOLIDATION", "Debt Consolidation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("purpose_description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AI_SCREENING", "AI Screening"),
                            ("RISK_REVIEWED", "Risk Reviewed"),
                            ("MANAGER_REVIEW", "Manager Review"),
                            ("COMMITTEE_REVIEW", "Committee Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MORE_INFO_REQUIRED", "More Information Required"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("officer_notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_applications",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "db_table": "loan_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashflowAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "other_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "existing_loan_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "proposed_monthly_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_cashflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("debt_to_income_ratio", models.FloatField(blank=True, null=True)),
                ("officer_assessment_notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflow",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "db_table": "cashflow_assessments",
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("changed_by_role", models.CharField(blank=True, max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_status_history",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LoanDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS_PLAN", "Business Plan"),
                            ("QUOTATION", "Quotation / Pro Forma Invoice"),
                            ("COLLATERAL_PHOTO", "Collateral Photo"),
                            ("COLLATERAL_VALUATION", "Collateral Valuation Report"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("TAX_RETURN", "Tax Return"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="loan_documents/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loan_documents",
            },
        ),
    ]
