# Generated by Django 6.0.4 on 2026-05-25 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by_agent", models.CharField(default="A2", max_length=10)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_memo",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "db_table": "credit_memos",
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.FloatField()),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("ai_rationale", models.TextField()),
                ("dti_score", models.FloatField(default=0)),
                ("lti_score", models.FloatField(default=0)),
                ("kyc_score", models.FloatField(default=0)),
                ("income_stability_score", models.FloatField(default=0)),
                ("repayment_history_score", models.FloatField(default=0)),
                ("dependents_score", models.FloatField(default=0)),
                ("default_signals", models.JSONField(default=list)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("analyst_notes", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "risk_assessments",
            },
        ),
        migrations.CreateModel(
            name="RiskScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.FloatField()),
                ("risk_category", models.CharField(max_length=10)),
                ("scored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_history",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "risk_score_history",
                "ordering": ["-scored_at"],
            },
        ),
    ]
