# Generated by Django 6.0.4 on 2026-05-29 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_creditmemo_riskassessment_riskscorehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("RECOMMEND_APPROVAL", "Recommend Approval"),
                            ("RECOMMEND_REJECTION", "Recommend Rejection"),
                            ("RECOMMEND_REDUCED_AMOUNT", "Recommend Reduced Amount"),
                            ("RECOMMEND_MORE_DOCUMENTS", "Recommend More Documents"),
                            ("RECOMMEND_ESCALATION", "Recommend Escalation to Manager"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "recommended_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "recommended_duration_months",
                    models.IntegerField(blank=True, null=True),
                ),
                ("explanation", models.TextField()),
                ("reasons", models.JSONField(default=list)),
                ("confidence", models.FloatField()),
                (
                    "officer_decision",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted AI Recommendation"),
                            ("OVERRIDDEN", "Overridden by Officer"),
                            ("PENDING", "Pending Review"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("officer_override_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendation",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_recommendations",
            },
        ),
        migrations.CreateModel(
            name="OfficerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_helpful", models.BooleanField()),
                ("comment", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="loans.airecommendation",
                    ),
                ),
            ],
            options={
                "db_table": "officer_feedback",
            },
        ),
    ]
