# Generated by Django 6.0.4 on 2026-05-31 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("loans", "0003_airecommendation_officerfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisbursementCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_text", models.CharField(max_length=255)),
                ("is_met", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursement_conditions",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "disbursement_conditions",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("duration_months", models.IntegerField()),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_repayable",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("DEFAULTED", "Defaulted"),
                            ("WRITTEN_OFF", "Written Off"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("disbursed_at", models.DateTimeField()),
                ("expected_closure_date", models.DateField()),
                ("actual_closure_date", models.DateField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "loans",
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("disbursed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursement",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursement_record",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "disbursements",
            },
        ),
    ]
