# Generated by Django 6.0.4 on 2026-06-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_disbursementcondition_loan_disbursement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("AI_SCREENING", "AI Screening"),
                    ("RISK_REVIEWED", "Risk Reviewed"),
                    ("MANAGER_REVIEW", "Manager Review"),
                    ("COMMITTEE_REVIEW", "Committee Review"),
                    ("APPROVED", "Approved"),
                    ("DISBURSED", "Disbursed"),
                    ("REJECTED", "Rejected"),
                    ("MORE_INFO_REQUIRED", "More Information Required"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
    ]
