# Generated by Django 6.0.4 on 2026-05-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("nic_number", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("phone_primary", models.CharField(max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("KYC_SUBMITTED", "KYC Submitted"),
                            ("VERIFIED", "Verified"),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("data_quality_score", models.FloatField(blank=True, null=True)),
                ("data_quality_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("BUSINESS", "Business"),
                            ("POSTAL", "Postal"),
                        ],
                        default="HOME",
                        max_length=20,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "client_addresses",
            },
        ),
        migrations.CreateModel(
            name="ClientBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("SOLE_PROPRIETOR", "Sole Proprietor"),
                            ("PARTNERSHIP", "Partnership"),
                            ("PRIVATE_LIMITED", "Private Limited"),
                            ("INFORMAL", "Informal Business"),
                            ("FARMING", "Farming"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_description", models.TextField(blank=True)),
                ("years_in_operation", models.IntegerField(default=0)),
                ("number_of_employees", models.IntegerField(default=0)),
                ("business_address", models.TextField(blank=True)),
                (
                    "monthly_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "client_businesses",
            },
        ),
        migrations.CreateModel(
            name="ClientIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        choices=[
                            ("BUSINESS", "Business Income"),
                            ("SALARY", "Salary"),
                            ("AGRICULTURE", "Agriculture"),
                            ("REMITTANCE", "Remittance"),
                            ("PENSION", "Pension"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "other_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "existing_debt_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("number_of_dependents", models.IntegerField(default=0)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "client_incomes",
            },
        ),
    ]
