# Generated by Django 6.0.4 on 2026-06-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("si", "Sinhala"), ("ta", "Tamil")],
                default="en",
                max_length=5,
            ),
        ),
    ]
