# Generated by Django 6.0.4 on 2026-06-05 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0004_disbursementcondition_loan_disbursement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelinquencyCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                            ("WRITTEN_OFF", "Written Off"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("days_overdue", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "predicted_default_probability",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "behavioral_pattern_label",
                    models.CharField(blank=True, max_length=30),
                ),
                ("llm_recommended_action", models.TextField(blank=True)),
                ("action_taken", models.TextField(blank=True)),
                ("officer_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delinquency_case",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "delinquency_cases",
                "ordering": ["-created_at"],
            },
        ),
    ]
