# Generated by Django 6.0.4 on 2026-06-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kpi_name", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("period", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "kpi_records",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PORTFOLIO", "Portfolio Summary"),
                            ("DEFAULT_RATE", "Default Rate"),
                            ("ARREARS", "Arrears Distribution"),
                            ("DISBURSEMENT", "Disbursement Summary"),
                            ("RISK_DISTRIBUTION", "Risk Score Distribution"),
                            ("AGENT_PERFORMANCE", "AI Agent Performance"),
                            ("FRAUD", "Fraud Alert Summary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.CharField(default="system", max_length=50)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "report_snapshots",
                "ordering": ["-generated_at"],
            },
        ),
    ]
