# Generated by Django 6.0.4 on 2026-06-02 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("loans", "0004_disbursementcondition_loan_disbursement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("DUPLICATE_IDENTITY", "Duplicate Identity Detected"),
                            ("APPLICATION_PATTERN", "Suspicious Application Pattern"),
                            ("PAYMENT_ANOMALY", "Payment Anomaly"),
                            ("UNUSUAL_AMOUNT", "Unusual Loan Amount"),
                            ("KYC_ANOMALY", "KYC Anomaly"),
                            ("BEHAVIORAL", "Suspicious Behavioral Pattern"),
                            ("MANUAL", "Manually Flagged"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_INVESTIGATION", "Under Investigation"),
                            ("CLEARED", "Cleared — No Fraud"),
                            ("CONFIRMED", "Fraud Confirmed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=25,
                    ),
                ),
                ("fraud_risk_score", models.FloatField(default=0.0)),
                ("ai_rationale", models.TextField()),
                ("detected_signals", models.JSONField(default=list)),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("triggered_by_agent", models.BooleanField(default=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("investigation_notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fraud_alerts",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_fraud_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fraud_alerts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "fraud_alerts",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CLEAR_CLIENT", "Clear Client — No Action"),
                            ("FLAG_CLIENT", "Flag Client for Monitoring"),
                            ("SUSPEND_APPLICATION", "Suspend Loan Application"),
                            ("FREEZE_ACCOUNT", "Freeze Client Account"),
                            ("REFER_LEGAL", "Refer to Legal Team"),
                            ("REPORT_AUTHORITY", "Report to Regulatory Authority"),
                            ("BLACKLIST_CLIENT", "Blacklist Client"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField()),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_actions",
                        to="fraud.fraudalert",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_actions",
            },
        ),
        migrations.CreateModel(
            name="FraudInvestigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("findings", models.TextField(blank=True)),
                ("evidence_collected", models.JSONField(default=list)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLEARED", "No Fraud Found"),
                            ("CONFIRMED", "Fraud Confirmed"),
                            ("INCONCLUSIVE", "Inconclusive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigation",
                        to="fraud.fraudalert",
                    ),
                ),
                (
                    "investigator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fraud_investigations",
            },
        ),
    ]
