# Generated by Django 6.0.4 on 2026-06-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fraud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraudalert",
            name="defense_findings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="investigation_focus",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="prosecutor_findings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
