# Generated by Django 6.0.4 on 2026-05-31 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0004_disbursementcondition_loan_disbursement"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_installments", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "repayment_schedules",
            },
        ),
        migrations.CreateModel(
            name="RepaymentInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.IntegerField()),
                ("due_date", models.DateField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "principal_component",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_component",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="repayments.repaymentschedule",
                    ),
                ),
            ],
            options={
                "db_table": "repayment_installments",
                "ordering": ["installment_number"],
            },
        ),
    ]
