# Generated by Django 6.0.4 on 2026-06-01 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_disbursementcondition_loan_disbursement"),
        ("repayments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repaymentinstallment",
            name="days_overdue",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repaymentinstallment",
            name="outstanding",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="installments_overdue",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repaymentschedule",
            name="installments_paid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="repaymentinstallment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partial Payment"),
                    ("OVERDUE", "Overdue"),
                    ("WAIVED", "Waived"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("is_penalty_payment", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="repayments.repaymentinstallment",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.JSONField(default=dict)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="repayments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payment_receipts",
            },
        ),
    ]
